version: "3.8"

# Bagian dari definisi semua service
services:
  # Definisi rabbitmq
  rabbitmq:
    # Menggunakan image rabbitmq
    image: rabbitmq:3.11-management
    # Nama dari service
    container_name: rabbitmq
    # Port dari rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    # Network untuk setiap service
    networks:
      - app_network

  # Definisi order-service
  order-service:
    # Menggunakan image rabbitmq
    image: ghcr.io/fitrahasfar/order-service:latest
    # Nama dari container
    container_name: order-service
    # Setup env dari amqp
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 3000
    # Port dari order-service
    ports:
      - 3000:3000
    # Harus menjalankan lebih dahulu rabbitmq lebih dahulu dan jalankan order-service
    depends_on:
      - rabbitmq
    # Network untuk setiap service
    networks:
      - app_network

  # Definisi shipping-service
  shipping-service:
    # Menggunakan image shipping-service
    image: ghcr.io/fitrahasfar/shipping-service:latest
    # Nama dari container
    container_name: shipping-service
    # Setup env dari amqp
    environment:
      AMQP_URL: amqp://rabbitmq:5672
      PORT: 3001
    # Port dari shipping-service
    ports:
      - 3001:3001
    # Harus menjalankan lebih dahulu rabbitmq lebih dahulu dan jalankan order-service
    depends_on:
      - rabbitmq
    # Network untuk setiap service
    networks:
      - app_network

# Network dari semua service
networks:
  app_network:
    driver: bridge
